image: maven:3-jdk-8

stages:
#  - sast
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

#sast:
#  stage: sast
#include:
#- template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - .m2/repository/
    - target/

maven-build:
  stage: build
  script: mvn compile

maven-test:
  stage: test
  script: mvn test
