stages:
#  - sast
  - build
  - test

services:
  - name: mongo:latest
    alias: mongodb
  - name: redis:latest
    alias: redis

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MONGODB_HOST: $MONGODB_HOST
  MONGODB_PORT: $MONGODB_PORT
  MONGODB_DB: $MONGODB_DB
  REDIS_HOST: $REDIS_HOST
  REDIS_PORT: $REDIS_PORT
  REDIS_PASSWORD: $REDIS_PASSWORD

#sast:
#  stage: sast
#include:
#- template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - .m2/repository/
    - target/

maven-build:
  image: maven:3.8.4-openjdk-17
  stage: build
  script: mvn compile

maven-test:
  image: maven:3.8.4-openjdk-17
  stage: test
  script: mvn test
