stages:
#  - sast
  - build
  - test

services:
  - name: mongo:latest
    alias: mongodb
  - name: redis:latest
    alias: redis

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: "27017"
  MONGODB_DB: "url-shortener"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"

#sast:
#  stage: sast
#include:
#- template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - .m2/repository/
    - target/

maven-build:
  image: maven:3.8.4-openjdk-17
  stage: build
  script: mvn compile

maven-test:
  image: maven:3.8.4-openjdk-17
  stage: test
  script: mvn test
